// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC45wFT8WRxPoM8XISwp8_8VdRdu_oMHqg',
    appId: '1:630042812801:web:0773ccd198e4ab3a82c880',
    messagingSenderId: '630042812801',
    projectId: 'qlcongviec-2cb9f',
    authDomain: 'qlcongviec-2cb9f.firebaseapp.com',
    storageBucket: 'qlcongviec-2cb9f.firebasestorage.app',
    measurementId: 'G-03NYH61QWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpaYrSpD9hZqCmSOygQvC_XtzCR7lHU1I',
    appId: '1:630042812801:android:e19c7f97bbb266e782c880',
    messagingSenderId: '630042812801',
    projectId: 'qlcongviec-2cb9f',
    storageBucket: 'qlcongviec-2cb9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmgNkpMKVgG0k3IQhDvdwJmrIdaH4PqD8',
    appId: '1:630042812801:ios:7eb689a0af69cc2782c880',
    messagingSenderId: '630042812801',
    projectId: 'qlcongviec-2cb9f',
    storageBucket: 'qlcongviec-2cb9f.firebasestorage.app',
    iosBundleId: 'com.example.btl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmgNkpMKVgG0k3IQhDvdwJmrIdaH4PqD8',
    appId: '1:630042812801:ios:7eb689a0af69cc2782c880',
    messagingSenderId: '630042812801',
    projectId: 'qlcongviec-2cb9f',
    storageBucket: 'qlcongviec-2cb9f.firebasestorage.app',
    iosBundleId: 'com.example.btl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC45wFT8WRxPoM8XISwp8_8VdRdu_oMHqg',
    appId: '1:630042812801:web:1720bfbba8c774d182c880',
    messagingSenderId: '630042812801',
    projectId: 'qlcongviec-2cb9f',
    authDomain: 'qlcongviec-2cb9f.firebaseapp.com',
    storageBucket: 'qlcongviec-2cb9f.firebasestorage.app',
    measurementId: 'G-0C85X0W5DB',
  );
}
